### ISSUE TITLE
Dotnet 6 Preview? :)

### ISSUE THREAD

**Issue by JessicaMulein** [csharptest/CSharpTest.Net.Collections#20]
```
 /usr/lib/mono/msbuild/Current/bin/NuGet.targets(128,5): error : Package CSharpTest.Net.Collections 14.906.1403.1082 is not compatible with net6.0 (.NETCoreApp,Version=v6.0). Package CSharpTest.Net.Collections 14.906.1403.1082 supports: [/home/runner/work/BrightChain/BrightChain/BrightChain.sln]
 ```

**Comment by NightOwl888** [comment]
Unfortunately, this project is no longer being maintained. So, there are a couple of alternatives for using it in .NET 6:

- Someone has cloned it and upgraded it to .NET Standard 2.0 as [CSharpTest.Net.Collections-NetStd2](https://www.nuget.org/packages/CSharpTest.Net.Collections-NetStd2/)
- We only required `LurchTable`, and created a cleaned-up version of it in [J2N.Collections.Concurrent](https://github.com/NightOwl888/J2N/tree/main/src/J2N/Collections/Concurrent). The `LurchTable` implementation now has similar APIs as `ConcurrentDictionary` and has been patched to work with Xamarin.iOS. The J2N library also contains other collection types that exist in Java, such as `LinkedDictionary` (similar to `LinkedHashMap`) and `LinkedHashSet`, which preserve insertion order of the items, and `PriorityQueue`. All of the collections in `J2N.Collections.Generic` support all of the same interfaces that Microsoft implements on their collections, nullable keys, structural equality (that is, the collections are compared for their contents using `Equals` and `GetHashCode` using rules specific to each collection family), and will print out their contents and nested contents when calling `ToString()`. The J2N project is being actively maintained.

**Comment by JessicaMulein** [comment]
Oh no, I'm sorry to hear that! It does compile although with a warning.

I'm mainly interested in BPlusTree. I may just use my now forked copy as a local library.

Thanks for letting me know!
